[tool.poetry]
name = "banker-buget"
version = "0.1.0"
description = ""
authors = ["martell dorsett"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
dash = "^2.14.2"
pandas = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
